import React from "react";
import {
  Brain,
  Search,
  Code2,
  Terminal,
  FileText,
  Clock,
  Eye,
  Palette,
  ShieldAlert,
  ShieldCheck,
  Activity,
  Cpu,
  Layers,
  Globe,
  Lock,
  FolderTree,
  Calendar,
  Table2,
  ScrollText,
  Scan,
  MousePointerClick,
  AppWindow,
  ScanText,
  Layout,
  Film,
  DownloadCloud,
  Ghost,
  BookMarked,
  Radio,
  RadioTower,
  Clapperboard,
  AlertCircle,
  Share2,
  Mic,
  Volume2,
  Mail,
  Languages,
  SlidersHorizontal,
  ListTodo,
  KeyRound,
  Boxes,
  FileCode2,
  Bug,
  GitMerge,
  Zap,
  BarChart3,
  Binary,
  RefreshCw,
  Target,
  Sparkles,
  Compass,
  Network,
  type LucideProps,
} from "lucide-react";
import { AGENT_MAP } from "../../constants/agents";

const ICON_MAP: Record<string, React.ComponentType<LucideProps>> = {
  // Lucide Icon Name mappings
  Brain,
  Search,
  Code2,
  Terminal,
  FileText,
  Clock,
  Eye,
  Palette,
  ShieldAlert,
  ShieldCheck,
  Activity,
  Cpu,
  Layers,
  Globe,
  Lock,
  FolderTree,
  Calendar,
  Table2,
  ScrollText,
  Scan,
  MousePointerClick,
  AppWindow,
  ScanText,
  Layout,
  Film,
  DownloadCloud,
  Ghost,
  BookMarked,
  Radio,
  RadioTower,
  Clapperboard,
  AlertCircle,
  Share2,
  Mic,
  Volume2,
  Mail,
  Languages,
  SlidersHorizontal,
  ListTodo,
  KeyRound,
  Boxes,
  FileCode2,
  Bug,
  GitMerge,
  Zap,
  BarChart3,
  Binary,
  RefreshCw,
  Target,
  Sparkles,
  Compass,
  Network,

  // Direct Agent ID mappings for quick lookups
  CHRONOS: Compass,
  MNEMONIC: Brain,
  AEGIS: ShieldAlert,
  SYNAPSE: Network,
  LUMEN: Sparkles,
  OMNI: Search,
  RESEARCH: Search,

  AXIS: Code2,
  CODING: Code2,
  CYPHER: FileCode2,
  CRUCIBLE: Bug,
  FORGE: Terminal,
  SANDBOX: Terminal,
  AUTOMATION: Terminal,
  NEXUS: GitMerge,
  ARGUS: ShieldCheck,
  APEX: Zap,
  QUANTA: BarChart3,
  TENSOR: Binary,
  GOLIATH: Boxes,
  PIVOT: RefreshCw,

  ATLAS: FolderTree,
  KINETIC: Calendar,
  PULSE: Activity,
  ZENITH: Target,
  LEDGER: Table2,
  VAULT: Lock,
  ECHO: ScrollText,
  WARDEN: ShieldAlert,
  PROXY: Globe,

  HAWK: Scan,
  TALON: MousePointerClick,
  PORTAL: AppWindow,
  IRIS: ScanText,
  VISION: ScanText,
  CANVAS: Layout,
  PRISM: Layers,
  RENDER: Film,
  SPECTRE: Eye,
  PICASSO: Palette,
  IMAGE: Palette,

  RAPTOR: DownloadCloud,
  PHANTOM: Ghost,
  VANGUARD: BookMarked,
  AETHER: Radio,
  BEACON: RadioTower,
  DIRECTOR: Clapperboard,
  GLITCH: AlertCircle,
  SPIDER: Share2,

  SONAR: Mic,
  ORACLE: Volume2,
  HERMES: Mail,
  AEON: Clock,
  POLYGLOT: Languages,
  SIREN: SlidersHorizontal,
  VORTEX: ListTodo,
  ENIGMA: KeyRound,
  KINESIS: FileText,
  DOCUMENT: FileText,

  CHAT: Sparkles,
  SYNTHESIZER: Sparkles,
};

interface AgentIconProps extends LucideProps {
  agentId?: string;
  iconName?: string;
}

export const AgentIcon: React.FC<AgentIconProps> = ({
  agentId,
  iconName,
  size = 16,
  className = "",
  ...props
}) => {
  let Component: React.ComponentType<LucideProps> = Sparkles;

  if (agentId && ICON_MAP[agentId.toUpperCase()]) {
    Component = ICON_MAP[agentId.toUpperCase()];
  } else if (iconName && ICON_MAP[iconName]) {
    Component = ICON_MAP[iconName];
  } else if (agentId && AGENT_MAP[agentId.toUpperCase()]?.icon) {
    const metaIcon = AGENT_MAP[agentId.toUpperCase()].icon;
    if (ICON_MAP[metaIcon]) {
      Component = ICON_MAP[metaIcon];
    }
  }

  return <Component size={size} className={className} {...props} />;
};
