export type Tier =
  | "MODEL_1_CORE"
  | "MODEL_2_CODE"
  | "MODEL_3_OS"
  | "MODEL_4_VISION"
  | "MODEL_5_WEB"
  | "MODEL_6_AUDIO";

export interface AgentMeta {
  id: string;
  name: string;
  tier: Tier;
  domain: string;
  blurb: string;
  icon: string;
  color: string;
  bg: string;
  border: string;
  text: string;
  model: string;
}

export const TIER_ORDER: Tier[] = [
  "MODEL_1_CORE",
  "MODEL_2_CODE",
  "MODEL_3_OS",
  "MODEL_4_VISION",
  "MODEL_5_WEB",
  "MODEL_6_AUDIO",
];

export const TIER_LABELS: Record<Tier, string> = {
  MODEL_1_CORE: "Core Reasoning & Planning",
  MODEL_2_CODE: "Software & Code Architecture",
  MODEL_3_OS: "OS & Desktop Automation",
  MODEL_4_VISION: "Vision, OCR & Screen RPA",
  MODEL_5_WEB: "Web Intelligence & Streaming",
  MODEL_6_AUDIO: "Audio, Speech & Documents",
};

export const TIER_COLORS: Record<Tier, string> = {
  MODEL_1_CORE: "#10b981", // Emerald
  MODEL_2_CODE: "#06b6d4", // Electric Cyan
  MODEL_3_OS: "#3b82f6",   // Sapphire Blue
  MODEL_4_VISION: "#ec4899", // Neon Pink
  MODEL_5_WEB: "#f59e0b",  // Molten Amber
  MODEL_6_AUDIO: "#a855f7", // Royal Purple
};

export const AGENTS: AgentMeta[] = [
  // ==========================================
  // TIER 1: Core Reasoning (MODEL_1_CORE)
  // ==========================================
  {
    id: "CHRONOS",
    name: "Chronos",
    tier: "MODEL_1_CORE",
    domain: "Architecture & Planning",
    blurb: "Breaks big asks into phased, dependency-aware roadmaps.",
    icon: "Compass",
    color: "#10b981",
    bg: "bg-emerald-950/30",
    border: "border-emerald-500/40",
    text: "text-emerald-400",
    model: "llama3.1:8b",
  },
  {
    id: "MNEMONIC",
    name: "Mnemonic",
    tier: "MODEL_1_CORE",
    domain: "Memory & Recall",
    blurb: "Stores and surfaces past decisions, preferences, and epistemic context.",
    icon: "Brain",
    color: "#14b8a6",
    bg: "bg-teal-950/30",
    border: "border-teal-500/40",
    text: "text-teal-400",
    model: "llama3.1:8b",
  },
  {
    id: "AEGIS",
    name: "Aegis",
    tier: "MODEL_1_CORE",
    domain: "Compliance & Safety Gate",
    blurb: "Guardian safety evaluation, security boundaries, and policy validation.",
    icon: "ShieldAlert",
    color: "#f59e0b",
    bg: "bg-amber-950/30",
    border: "border-amber-500/40",
    text: "text-amber-400",
    model: "llama3.1:8b",
  },
  {
    id: "SYNAPSE",
    name: "Synapse",
    tier: "MODEL_1_CORE",
    domain: "Task Orchestration",
    blurb: "Dynamic task routing, sub-agent coordination, and dispatch.",
    icon: "Network",
    color: "#22c55e",
    bg: "bg-green-950/30",
    border: "border-green-500/40",
    text: "text-green-400",
    model: "llama3.1:8b",
  },
  {
    id: "LUMEN",
    name: "Lumen",
    tier: "MODEL_1_CORE",
    domain: "Ideation & Creative",
    blurb: "Generates lateral thinking, hypothesis exploration, and creative solutions.",
    icon: "Sparkles",
    color: "#fbbf24",
    bg: "bg-yellow-950/30",
    border: "border-yellow-500/40",
    text: "text-yellow-400",
    model: "llama3.1:8b",
  },
  {
    id: "OMNI",
    name: "Omni",
    tier: "MODEL_1_CORE",
    domain: "Deep Research & Data Analysis",
    blurb: "Epistemic source analysis, statistical extraction, and multi-document reasoning.",
    icon: "Search",
    color: "#f97316",
    bg: "bg-orange-950/30",
    border: "border-orange-500/40",
    text: "text-orange-400",
    model: "deepseek-r1:7b",
  },

  // ==========================================
  // TIER 2: Code Engineering (MODEL_2_CODE)
  // ==========================================
  {
    id: "AXIS",
    name: "Axis",
    tier: "MODEL_2_CODE",
    domain: "Forge AI Software Architect",
    blurb: "Autonomous full-stack engineering, visualization scripts, and algorithms.",
    icon: "Code2",
    color: "#06b6d4",
    bg: "bg-cyan-950/30",
    border: "border-cyan-500/40",
    text: "text-cyan-400",
    model: "qwen2.5-coder:7b",
  },
  {
    id: "CYPHER",
    name: "Cypher",
    tier: "MODEL_2_CODE",
    domain: "Code Generation",
    blurb: "Rapid implementation code, boilerplate synthesis, and clean typing.",
    icon: "FileCode2",
    color: "#0ea5e9",
    bg: "bg-sky-950/30",
    border: "border-sky-500/40",
    text: "text-sky-400",
    model: "qwen2.5-coder:7b",
  },
  {
    id: "CRUCIBLE",
    name: "Crucible",
    tier: "MODEL_2_CODE",
    domain: "Debugging & Forensics",
    blurb: "Locates root cause of stack traces, memory leaks, and runtime errors.",
    icon: "Bug",
    color: "#ef4444",
    bg: "bg-red-950/30",
    border: "border-red-500/40",
    text: "text-red-400",
    model: "qwen2.5-coder:7b",
  },
  {
    id: "FORGE",
    name: "Forge",
    tier: "MODEL_2_CODE",
    domain: "System & Sandbox Execution",
    blurb: "Sandboxed execution of scripts, schema modeling, and API scaffolding.",
    icon: "Terminal",
    color: "#3b82f6",
    bg: "bg-blue-950/30",
    border: "border-blue-500/40",
    text: "text-blue-400",
    model: "mistral:7b",
  },
  {
    id: "NEXUS",
    name: "Nexus",
    tier: "MODEL_2_CODE",
    domain: "DAG Planner & Version Control",
    blurb: "Decomposes complex requests into collaborative sub-task graphs.",
    icon: "GitMerge",
    color: "#8b5cf6",
    bg: "bg-violet-950/30",
    border: "border-violet-500/40",
    text: "text-violet-400",
    model: "deepseek-r1:7b",
  },
  {
    id: "ARGUS",
    name: "Argus",
    tier: "MODEL_2_CODE",
    domain: "Security & Vulnerability Audit",
    blurb: "Audits code for injection risks, unsafe pointers, and dependency flaws.",
    icon: "ShieldCheck",
    color: "#e11d48",
    bg: "bg-rose-950/30",
    border: "border-rose-500/40",
    text: "text-rose-400",
    model: "qwen2.5-coder:7b",
  },
  {
    id: "APEX",
    name: "Apex",
    tier: "MODEL_2_CODE",
    domain: "Performance Optimization",
    blurb: "Analyzes algorithmic complexity (Big-O) and minimizes latency.",
    icon: "Zap",
    color: "#10b981",
    bg: "bg-emerald-950/30",
    border: "border-emerald-500/40",
    text: "text-emerald-400",
    model: "qwen2.5-coder:7b",
  },
  {
    id: "QUANTA",
    name: "Quanta",
    tier: "MODEL_2_CODE",
    domain: "Data Science & Statistics",
    blurb: "Data transformation pipelines, numpy arrays, and statistical modeling.",
    icon: "BarChart3",
    color: "#6366f1",
    bg: "bg-indigo-950/30",
    border: "border-indigo-500/40",
    text: "text-indigo-400",
    model: "qwen2.5-coder:7b",
  },
  {
    id: "TENSOR",
    name: "Tensor",
    tier: "MODEL_2_CODE",
    domain: "Algorithmic Math & AI",
    blurb: "Linear algebra, neural network architectures, and numerical solvers.",
    icon: "Binary",
    color: "#ec4899",
    bg: "bg-pink-950/30",
    border: "border-pink-500/40",
    text: "text-pink-400",
    model: "qwen2.5-coder:7b",
  },
  {
    id: "GOLIATH",
    name: "Goliath",
    tier: "MODEL_2_CODE",
    domain: "DevOps & Containers",
    blurb: "Docker compose setups, CI/CD pipelines, and infrastructure manifests.",
    icon: "Boxes",
    color: "#64748b",
    bg: "bg-slate-900/60",
    border: "border-slate-700/60",
    text: "text-slate-300",
    model: "mistral:7b",
  },
  {
    id: "PIVOT",
    name: "Pivot",
    tier: "MODEL_2_CODE",
    domain: "Refactoring & Clean Architecture",
    blurb: "Eliminates technical debt, applies SOLID patterns, and cleans legacy code.",
    icon: "RefreshCw",
    color: "#22c55e",
    bg: "bg-green-950/30",
    border: "border-green-500/40",
    text: "text-green-400",
    model: "qwen2.5-coder:7b",
  },

  // ==========================================
  // TIER 3: OS & System Automation (MODEL_3_OS)
  // ==========================================
  {
    id: "ATLAS",
    name: "Atlas",
    tier: "MODEL_3_OS",
    domain: "Filesystem & Storage",
    blurb: "Organizes directories, cleans junk artifacts, and manages disk space.",
    icon: "FolderTree",
    color: "#0ea5e9",
    bg: "bg-sky-950/30",
    border: "border-sky-500/40",
    text: "text-sky-400",
    model: "mistral:7b",
  },
  {
    id: "KINETIC",
    name: "Kinetic",
    tier: "MODEL_3_OS",
    domain: "Chronos Task Triggers",
    blurb: "Background jobs, interval triggers, and automated cron pipelines.",
    icon: "Calendar",
    color: "#f59e0b",
    bg: "bg-amber-950/30",
    border: "border-amber-500/40",
    text: "text-amber-400",
    model: "llama3.1:8b",
  },
  {
    id: "PULSE",
    name: "Pulse",
    tier: "MODEL_3_OS",
    domain: "Hardware & VRAM Sentinel",
    blurb: "Monitors GPU VRAM, CPU load, temperature, and runaway processes.",
    icon: "Activity",
    color: "#10b981",
    bg: "bg-emerald-950/30",
    border: "border-emerald-500/40",
    text: "text-emerald-400",
    model: "mistral:7b",
  },
  {
    id: "ZENITH",
    name: "Zenith",
    tier: "MODEL_3_OS",
    domain: "Focus & Workstation Flow",
    blurb: "Manages productive workspace states and window arrangements.",
    icon: "Target",
    color: "#8b5cf6",
    bg: "bg-violet-950/30",
    border: "border-violet-500/40",
    text: "text-violet-400",
    model: "mistral:7b",
  },
  {
    id: "LEDGER",
    name: "Ledger",
    tier: "MODEL_3_OS",
    domain: "Dataset & CSV Operations",
    blurb: "Direct tabular queries, CSV filtering, and data sanitization.",
    icon: "Table2",
    color: "#eab308",
    bg: "bg-yellow-950/30",
    border: "border-yellow-500/40",
    text: "text-yellow-400",
    model: "mistral:7b",
  },
  {
    id: "VAULT",
    name: "Vault",
    tier: "MODEL_3_OS",
    domain: "Secrets & Keyrings",
    blurb: "Safely encrypts environment secrets and credential stores.",
    icon: "Lock",
    color: "#ef4444",
    bg: "bg-red-950/30",
    border: "border-red-500/40",
    text: "text-red-400",
    model: "mistral:7b",
  },
  {
    id: "ECHO",
    name: "Echo",
    tier: "MODEL_3_OS",
    domain: "Telemetry & Logs",
    blurb: "Aggregates application logs and parses system event traces.",
    icon: "ScrollText",
    color: "#64748b",
    bg: "bg-slate-900/60",
    border: "border-slate-700/60",
    text: "text-slate-300",
    model: "mistral:7b",
  },
  {
    id: "WARDEN",
    name: "Warden",
    tier: "MODEL_3_OS",
    domain: "Firewall & Egress Defense",
    blurb: "Enforces 100% offline localhost boundary and blocks unverified ports.",
    icon: "ShieldAlert",
    color: "#dc2626",
    bg: "bg-red-950/30",
    border: "border-red-600/40",
    text: "text-red-400",
    model: "mistral:7b",
  },
  {
    id: "PROXY",
    name: "Proxy",
    tier: "MODEL_3_OS",
    domain: "Network & Port Management",
    blurb: "Configures reverse proxies, localhost routes, and WebSockets.",
    icon: "Globe",
    color: "#06b6d4",
    bg: "bg-cyan-950/30",
    border: "border-cyan-500/40",
    text: "text-cyan-400",
    model: "mistral:7b",
  },

  // ==========================================
  // TIER 4: Vision & Screen RPA (MODEL_4_VISION)
  // ==========================================
  {
    id: "HAWK",
    name: "Hawk",
    tier: "MODEL_4_VISION",
    domain: "Screen Vision & Bounding Boxes",
    blurb: "Detects UI coordinates, buttons, and visual anomalies from screenshots.",
    icon: "Scan",
    color: "#ec4899",
    bg: "bg-pink-950/30",
    border: "border-pink-500/40",
    text: "text-pink-400",
    model: "qwen2-vl:7b",
  },
  {
    id: "TALON",
    name: "Talon",
    tier: "MODEL_4_VISION",
    domain: "RPA Automation",
    blurb: "Executes precise keyboard keystrokes and pointer clicks.",
    icon: "MousePointerClick",
    color: "#f43f5e",
    bg: "bg-rose-950/30",
    border: "border-rose-500/40",
    text: "text-rose-400",
    model: "mistral:7b",
  },
  {
    id: "PORTAL",
    name: "Portal",
    tier: "MODEL_4_VISION",
    domain: "App Window Focus",
    blurb: "Launches, focuses, docks, and arranges desktop application windows.",
    icon: "AppWindow",
    color: "#a855f7",
    bg: "bg-purple-950/30",
    border: "border-purple-500/40",
    text: "text-purple-400",
    model: "mistral:7b",
  },
  {
    id: "IRIS",
    name: "Iris",
    tier: "MODEL_4_VISION",
    domain: "OCR & Document Vision",
    blurb: "Extracts structured text and tables from scans, PDFs, and screen captures.",
    icon: "ScanText",
    color: "#d946ef",
    bg: "bg-fuchsia-950/30",
    border: "border-fuchsia-500/40",
    text: "text-fuchsia-400",
    model: "qwen2-vl:7b",
  },
  {
    id: "CANVAS",
    name: "Canvas",
    tier: "MODEL_4_VISION",
    domain: "UI/UX Wireframes",
    blurb: "Visual design layouts, wireframes, and component palettes.",
    icon: "Layout",
    color: "#3b82f6",
    bg: "bg-blue-950/30",
    border: "border-blue-500/40",
    text: "text-blue-400",
    model: "llama3.1:8b",
  },
  {
    id: "PRISM",
    name: "Prism",
    tier: "MODEL_4_VISION",
    domain: "Image Processing",
    blurb: "Batch crops, color filters, and resizes image assets via CLI.",
    icon: "Layers",
    color: "#8b5cf6",
    bg: "bg-violet-950/30",
    border: "border-violet-500/40",
    text: "text-violet-400",
    model: "mistral:7b",
  },
  {
    id: "RENDER",
    name: "Render",
    tier: "MODEL_4_VISION",
    domain: "Media Transcoding",
    blurb: "FFmpeg arguments, audio/video encoding, and stream pipelines.",
    icon: "Film",
    color: "#f97316",
    bg: "bg-orange-950/30",
    border: "border-orange-500/40",
    text: "text-orange-400",
    model: "mistral:7b",
  },
  {
    id: "SPECTRE",
    name: "Spectre",
    tier: "MODEL_4_VISION",
    domain: "Visual QA & Regressions",
    blurb: "Compares UI snapshots to detect visual regressions and pixel shifts.",
    icon: "Inspect",
    color: "#14b8a6",
    bg: "bg-teal-950/30",
    border: "border-teal-500/40",
    text: "text-teal-400",
    model: "qwen2-vl:7b",
  },
  {
    id: "PICASSO",
    name: "Picasso",
    tier: "MODEL_4_VISION",
    domain: "Image Synthesis Studio",
    blurb: "Generates creative illustrations, banners, and graphical visual assets.",
    icon: "Palette",
    color: "#fbbf24",
    bg: "bg-yellow-950/30",
    border: "border-yellow-500/40",
    text: "text-yellow-400",
    model: "llama3.1:8b",
  },

  // ==========================================
  // TIER 5: Web & Streaming (MODEL_5_WEB)
  // ==========================================
  {
    id: "RAPTOR",
    name: "Raptor",
    tier: "MODEL_5_WEB",
    domain: "HTML Scraping",
    blurb: "Extracts clean markdown and structured text from static web pages.",
    icon: "DownloadCloud",
    color: "#22c55e",
    bg: "bg-green-950/30",
    border: "border-green-500/40",
    text: "text-green-400",
    model: "mistral:7b",
  },
  {
    id: "PHANTOM",
    name: "Phantom",
    tier: "MODEL_5_WEB",
    domain: "Headless Browser Automation",
    blurb: "Drives Playwright sessions on dynamic, JS-heavy web interfaces.",
    icon: "Ghost",
    color: "#6366f1",
    bg: "bg-indigo-950/30",
    border: "border-indigo-500/40",
    text: "text-indigo-400",
    model: "mistral:7b",
  },
  {
    id: "VANGUARD",
    name: "Vanguard",
    tier: "MODEL_5_WEB",
    domain: "Web Intelligence & Docs",
    blurb: "Discovers documentation, release notes, and engineering benchmarks.",
    icon: "BookMarked",
    color: "#0ea5e9",
    bg: "bg-sky-950/30",
    border: "border-sky-500/40",
    text: "text-sky-400",
    model: "deepseek-r1:7b",
  },
  {
    id: "AETHER",
    name: "Aether",
    tier: "MODEL_5_WEB",
    domain: "Media Extraction",
    blurb: "Fetches transcripts and media streams from public video platforms.",
    icon: "Radio",
    color: "#a855f7",
    bg: "bg-purple-950/30",
    border: "border-purple-500/40",
    text: "text-purple-400",
    model: "mistral:7b",
  },
  {
    id: "BEACON",
    name: "Beacon",
    tier: "MODEL_5_WEB",
    domain: "Live Stream Poller",
    blurb: "Monitors status changes and updates from real-time feeds.",
    icon: "RadioTower",
    color: "#10b981",
    bg: "bg-emerald-950/30",
    border: "border-emerald-500/40",
    text: "text-emerald-400",
    model: "mistral:7b",
  },
  {
    id: "DIRECTOR",
    name: "Director",
    tier: "MODEL_5_WEB",
    domain: "Broadcast & OBS Controller",
    blurb: "Controls scene switches, recording states, and stream layouts.",
    icon: "Clapperboard",
    color: "#f43f5e",
    bg: "bg-rose-950/30",
    border: "border-rose-500/40",
    text: "text-rose-400",
    model: "mistral:7b",
  },
  {
    id: "GLITCH",
    name: "Glitch",
    tier: "MODEL_5_WEB",
    domain: "Autonomous Error Healing",
    blurb: "Catches failure exceptions and retries with alternative fallback paths.",
    icon: "AlertCircle",
    color: "#f59e0b",
    bg: "bg-amber-950/30",
    border: "border-amber-500/40",
    text: "text-amber-400",
    model: "mistral:7b",
  },
  {
    id: "SPIDER",
    name: "Spider",
    tier: "MODEL_5_WEB",
    domain: "Web Crawler & Indexer",
    blurb: "Traverses site hierarchies to build comprehensive documentation indexes.",
    icon: "Share2",
    color: "#06b6d4",
    bg: "bg-cyan-950/30",
    border: "border-cyan-500/40",
    text: "text-cyan-400",
    model: "mistral:7b",
  },

  // ==========================================
  // TIER 6: Audio & Language (MODEL_6_AUDIO)
  // ==========================================
  {
    id: "SONAR",
    name: "Sonar",
    tier: "MODEL_6_AUDIO",
    domain: "Speech-to-Text (Whisper)",
    blurb: "Ultra-fast local voice transcription with timestamp precision.",
    icon: "Mic",
    color: "#06b6d4",
    bg: "bg-cyan-950/30",
    border: "border-cyan-500/40",
    text: "text-cyan-400",
    model: "whisper-base",
  },
  {
    id: "ORACLE",
    name: "Oracle",
    tier: "MODEL_6_AUDIO",
    domain: "Text-to-Speech (Piper)",
    blurb: "Natural, low-latency neural speech synthesis for voice feedback.",
    icon: "Volume2",
    color: "#8b5cf6",
    bg: "bg-violet-950/30",
    border: "border-violet-500/40",
    text: "text-violet-400",
    model: "piper-tts",
  },
  {
    id: "HERMES",
    name: "Hermes",
    tier: "MODEL_6_AUDIO",
    domain: "Correspondence & Tone",
    blurb: "Composes formal emails, letters, and tailored communication.",
    icon: "Mail",
    color: "#3b82f6",
    bg: "bg-blue-950/30",
    border: "border-blue-500/40",
    text: "text-blue-400",
    model: "llama3.1:8b",
  },
  {
    id: "AEON",
    name: "Aeon",
    tier: "MODEL_6_AUDIO",
    domain: "Temporal & Event Logistics",
    blurb: "Manages cross-timezone appointments, durations, and reminders.",
    icon: "Clock",
    color: "#f59e0b",
    bg: "bg-amber-950/30",
    border: "border-amber-500/40",
    text: "text-amber-400",
    model: "llama3.1:8b",
  },
  {
    id: "POLYGLOT",
    name: "Polyglot",
    tier: "MODEL_6_AUDIO",
    domain: "Translation & Localization",
    blurb: "Translates and localizes multilingual documents and dialogues.",
    icon: "Languages",
    color: "#10b981",
    bg: "bg-emerald-950/30",
    border: "border-emerald-500/40",
    text: "text-emerald-400",
    model: "qwen2.5:7b",
  },
  {
    id: "SIREN",
    name: "Siren",
    tier: "MODEL_6_AUDIO",
    domain: "Audio DSP & Equalization",
    blurb: "Applies high-pass noise gates, audio normalization, and sound levels.",
    icon: "SlidersHorizontal",
    color: "#ec4899",
    bg: "bg-pink-950/30",
    border: "border-pink-500/40",
    text: "text-pink-400",
    model: "mistral:7b",
  },
  {
    id: "VORTEX",
    name: "Vortex",
    tier: "MODEL_6_AUDIO",
    domain: "Meeting Synthesis",
    blurb: "Distills hours of meeting transcripts into clear executive action items.",
    icon: "ListTodo",
    color: "#14b8a6",
    bg: "bg-teal-950/30",
    border: "border-teal-500/40",
    text: "text-teal-400",
    model: "deepseek-r1:7b",
  },
  {
    id: "ENIGMA",
    name: "Enigma",
    tier: "MODEL_6_AUDIO",
    domain: "Cryptography & Signing",
    blurb: "Digitally signs documents and hashes sensitive authentication tokens.",
    icon: "KeyRound",
    color: "#ef4444",
    bg: "bg-red-950/30",
    border: "border-red-500/40",
    text: "text-red-400",
    model: "mistral:7b",
  },
  {
    id: "KINESIS",
    name: "Kinesis",
    tier: "MODEL_6_AUDIO",
    domain: "Document Architecture & Synthesis",
    blurb: "Authors professional PDF reports, Word DOCX, Markdown, HTML, and CSVs.",
    icon: "FileText",
    color: "#a855f7",
    bg: "bg-purple-950/30",
    border: "border-purple-500/40",
    text: "text-purple-400",
    model: "qwen2.5:7b",
  },
];

export const AGENT_MAP: Record<string, AgentMeta> = Object.fromEntries(
  AGENTS.map((a) => [a.id, a]),
);
